# Commit Verification CI
# Verifies transient and automated commits in PRs
#
# - Transient commits (prefix: "transient: ") must have zero net effect
# - Automated commits (prefix: "x: <command>") must match command output
# - Uploads a workflow artifact with verification status and a comment to be posted on the PR

name: Commit Verification

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Cancel in-progress runs for the same PR
concurrency:
  group: commit-verification-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TRANSIENT_PREFIX: "transient: "
  AUTO_PREFIX: "x: "

jobs:
  verify:
    name: Verify Transient and Automated Commits
    runs-on: ubuntu-latest
    # Only run if there are commits with special prefixes
    # This is a quick check to avoid unnecessary runs
    steps:
      - name: Checkout default branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: master
          path: master-branch

      - name: Checkout PR head
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Checkout the actual PR head, not the merge commit GitHub creates
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch full history to access all PR commits
          fetch-depth: 0
          path: pr-branch

      - name: Check for special commits
        id: check
        working-directory: pr-branch
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"

          # Check if any commits have transient or auto prefix
          HAS_SPECIAL=$(git log --format="%s" "$BASE_SHA..$HEAD_SHA" | \
            grep -E "^(${TRANSIENT_PREFIX}|${AUTO_PREFIX})" || true)

          if [[ -n "$HAS_SPECIAL" ]]; then
            echo "has_special=true" >> "$GITHUB_OUTPUT"
            echo "Found commits requiring verification:"
            echo "$HAS_SPECIAL"
          else
            echo "has_special=false" >> "$GITHUB_OUTPUT"
            echo "No transient or automated commits found"
          fi

      - name: Verify commits
        id: verify
        if: steps.check.outputs.has_special == 'true'
        working-directory: pr-branch
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"

          # Run verification (human-readable to stdout, JSON to file)
          set +e
          ../master-branch/scripts/verify_commits.sh "$BASE_SHA" --json-file verification_result.json
          EXIT_CODE=$?
          set -e

          # Set outputs
          if [[ $EXIT_CODE -eq 0 ]]; then
            echo "success=true" >> "$GITHUB_OUTPUT"
          else
            echo "success=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate PR comment
        if: steps.check.outputs.has_special == 'true'
        id: comment
        working-directory: pr-branch
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          COMMENT=$(cat verification_result.json | ../master-branch/scripts/verify_commits_summary.sh "$REPO" "$PR_NUMBER")

          # Save to file (GitHub Actions has issues with multiline outputs)
          echo "$COMMENT" > comment_body.md

      - name: Prepare bridge outputs
        if: steps.check.outputs.has_special == 'true'
        run: |
          jq -n \
            --arg has_special "${{ steps.check.outputs.has_special }}" \
            --arg success "${{ steps.verify.outputs.success }}" \
            '{
              has_special: $has_special,
              success: $success,
            }' > bridge-outputs.json

      - name: Emit bridge artifact
        if: steps.check.outputs.has_special == 'true'
        uses: leanprover-community/privilege-escalation-bridge/emit@v1
        with:
          artifact: workflow-data
          outputs_file: bridge-outputs.json
          include_event: minimal
          files: |
            pr-branch/comment_body.md
          retention_days: 5
