name: Maintainer merge (workflow_run)

# triggers the action when
on:
  workflow_run:
    workflows: ["Maintainer merge"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  ping_zulip:
    name: Ping maintainers on Zulip
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'leanprover-community/mathlib4' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.MATHLIB_TRIAGE_APP_ID }}
          private-key: ${{ secrets.MATHLIB_TRIAGE_PRIVATE_KEY }}

      - name: Consume bridge artifact
        id: bridge
        uses: leanprover-community/privilege-escalation-bridge/consume@v1
        with:
          artifact: workflow-data
          source_workflow: Maintainer merge
          expected_head_sha: ${{ github.event.workflow_run.head_sha }}
          require_event: issue_comment,pull_request_review,pull_request_review_comment
          fail_on_missing: false
          extract: |
            author=event.comment.user.login|event.review.user.login
            pr_author=event.issue.user.login|event.pull_request.user.login
            pr_number=meta.pr_number
            comment=event.comment.body|event.review.body
            pr_title=event.issue.title|event.pull_request.title
            pr_url=event.issue.html_url|event.pull_request.html_url
            event_name=meta.event_name
            mOrD=outputs.mOrD

      - if: ${{ ! steps.bridge.outputs.mOrD == '' }}
        name: Check whether user is part of mathlib-reviewers team
        uses: tspascoal/get-user-teams-membership@57e9f42acd78f4d0f496b3be4368fc5f62696662 # v3.0.0
        id: actorTeams
        with:
          organization: leanprover-community # optional. Default value ${{ github.repository_owner }}
                  # Organization to get membership from.
          team: 'mathlib-reviewers'
          username: ${{ steps.bridge.outputs.author }}
          GITHUB_TOKEN: ${{ secrets.MATHLIB_REVIEWERS_TEAM_KEY }} # (Requires scope: `read:org`)

      - name: Checkout
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: master
          sparse-checkout: |
            scripts/get_tlabel.py
            scripts/maintainer_merge_message.py

      - name: Determine Zulip topic
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        id: determine_topic
        run: |
          ./scripts/get_tlabel.sh "/repos/leanprover-community/mathlib4/issues/${PR_NUMBER}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ steps.bridge.outputs.pr_number }}

      - name: Form the message
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        id: form_the_message
        run: |
          message="$(
            ./scripts/maintainer_merge_message.sh "${AUTHOR}" "${{ steps.bridge.outputs.mOrD }}" "${EVENT_NAME}" "${PR_NUMBER}" "${PR_URL}" "${PR_TITLE}" "${COMMENT}" "${PR_AUTHOR}"
          )"
          printf 'title<<EOF\n%s\nEOF' "${message}" | tee "$GITHUB_OUTPUT"
        env:
          AUTHOR: ${{ steps.bridge.outputs.author }}
          EVENT_NAME: ${{ steps.bridge.outputs.event_name }}
          PR_NUMBER: ${{ steps.bridge.outputs.pr_number }}
          PR_URL: ${{ steps.bridge.outputs.pr_url }}
          PR_TITLE: ${{ steps.bridge.outputs.pr_title }}
          COMMENT: ${{ steps.bridge.outputs.comment }}
          PR_AUTHOR: ${{ steps.bridge.outputs.pr_author }}

      - name: Send message on Zulip
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib reviewers'
          type: 'stream'
          topic: ${{ steps.determine_topic.outputs.topic }}
          content: ${{ steps.form_the_message.outputs.title }}

      - name: Add comment to PR
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        uses: GrantBirki/comment@608e41b19bc973020ec0e189ebfdae935d7fe0cc # v2.1.1
        with:
          # if a comment triggers the action, then `issue.number` is set
          # if a review or review comment triggers the action, then `pull_request.number` is set
          issue-number: ${{ steps.bridge.outputs.pr_number }}
          body: |
            🚀 Pull request has been placed on the maintainer queue by ${{ steps.bridge.outputs.author }}.

      - name: Add label to PR
        if: ${{ steps.actorTeams.outputs.isTeamMember == 'true' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          # labels added by GITHUB_TOKEN won't trigger the Zulip emoji workflow
          # The create-github-app-token README states that this token is masked and will not be logged accidentally.
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = ${{ steps.bridge.outputs.pr_number }};
            await github.rest.issues.addLabels({ owner, repo, issue_number, labels: ['maintainer-merge'] });
