name: Create single-file PR from review comment (Reusable)

on:
  workflow_call:
    inputs:
      base_ref:
        description: 'Base branch to compare against (optional)'
        required: false
        type: string
        default: master
      committer:
        description: >
          The committer name and email address in the format `Display Name <email@address.com>`.
          Defaults to the GitHub Actions bot user.
        required: false
        type: string
        default: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
      author:
        description: >
          The author name and email address in the format `Display Name <email@address.com>`.
          Defaults to the author of the PR.
        required: false
        type: string
        default: '${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>'

permissions: {}

jobs:
  create-single-file-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Verify caller event is pull_request_review_comment
        uses: actions/github-script@v7
        with:
          script: |
            const eventName = context.eventName;
            const hasReviewCommentPayload = !!(context.payload?.comment && context.payload?.pull_request);

            if (eventName !== "pull_request_review_comment" && !hasReviewCommentPayload) {
              core.setFailed(
                `This workflow must be called from a pull_request_review_comment trigger; got ${eventName}.`
              );
              return;
            }

            core.info(`Trigger OK: ${eventName}`);

      - name: Extract essentials from event (and optionally filter for suggestions)
        id: extract
        uses: actions/github-script@v7
        env:
          # Pass the reusable input down to the script and emit it as an output named base_ref
          BASE_REF_INPUT: ${{ inputs.base_ref }}
        with:
          script: |
            // NOTE: In actions/github-script, `core`, `github`, and `context` are provided globally.
            const comment = context.payload?.comment;
            const pr = context.payload?.pull_request;
            const body = comment?.body || "";

            core.info(`Comment body:\n---\n${body}\n---`);

            // Start-of-line match across lines; no leading whitespace allowed
            if (!/^splice-bot\b/im.test(body)) {
              core.info("No `splice-bot` found at the start of a line, skipping.");
              core.setOutput("skip", "true");
              return;
            }

            const path = comment?.path;
            if (!path) {
              core.info("This review comment is not on a file diff (no .path). Nothing to do.");
              core.setOutput("skip", "true");
              return;
            }

            if (!pr) {
              core.info("No pull_request object on this event.");
              core.setOutput("skip", "true");
              return;
            }

            // Gather PR metadata (for logging and outputs)
            const prNumber = pr.number;
            const baseSha = pr.base?.sha;
            const baseRepoFullName = pr.base?.repo?.full_name;
            const headSha = pr.head?.sha;
            const headRepoFullName = pr.head?.repo?.full_name;

            if (!baseSha || !headSha || !baseRepoFullName || !headRepoFullName) {
              core.info("Missing required PR details (base/head sha/repo).");
              core.setOutput("skip", "true");
              return;
            }

            const filename = path.split("/").pop();
            const baseRefFromInput = process.env.BASE_REF_INPUT || "master";

            core.info(`File path: ${path}`);
            core.info(`Filename: ${filename}`);
            core.info(`PR #${prNumber} | base: ${baseRefFromInput} | head sha: ${headSha}`);
            core.info(`head repo: ${headRepoFullName} | base repo: ${baseRepoFullName}`);

            // Outputs preserved for downstream steps
            core.setOutput("skip", "false");
            // IMPORTANT: base_ref now comes from the reusable workflow input (default master)
            core.setOutput("base_ref", baseRefFromInput);

      - if: ${{ steps.extract.outputs.skip != 'true' }}
        name: Prepare bridge outputs
        run: |
          jq -n \
            --arg base_ref "${{ steps.extract.outputs.base_ref }}" \
            --arg committer "${{ inputs.committer }}" \
            --arg author "${{ inputs.author }}" \
            '{
              base_ref: $base_ref,
              committer: $committer,
              author: $author,
            }' > bridge-outputs.json

      - if: ${{ steps.extract.outputs.skip != 'true' }}
        name: Emit bridge artifact
        uses: leanprover-community/privilege-escalation-bridge/emit@v1
        with:
          artifact: workflow-data
          outputs_file: bridge-outputs.json
          include_event: minimal
          retention_days: 5
